name: Test Docker Push

on:
  push:
    branches:
      - master

jobs:
  test-docker-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Verify JSON content
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcloud-key.json
        echo "Contents of the JSON file:"
        cat /tmp/gcloud-key.json

    - name: Authenticate Google Cloud
      run: |
        # Reemplazar \n por saltos de línea reales y guardar en /tmp/gcloud-key.json
        echo "${{ secrets.GCP_SA_KEY }}" | sed 's/\\n/\n/g' > /tmp/gcloud-key.json
        
        # Mostrar el contenido del archivo para verificar que se ha formateado correctamente
        echo "Formatted JSON content:"
        cat /tmp/gcloud-key.json
        
        # Intentar autenticarse con Google Cloud usando el archivo JSON corregido
        gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
        
        # Configurar Docker para utilizar la autenticación con Google Cloud
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        
        # Listar las cuentas autenticadas
        gcloud auth list

    - name: Build the Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app .

    - name: Push the Docker image
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app

