name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.9.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: your-project-id

    - name: Verify JSON content
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcloud-key.json
        echo "Contents of the JSON file:"
        cat /tmp/gcloud-key.json

    - name: Authenticate Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/your-project-id/your-repo-name/your-image-name:latest .
        docker push us-central1-docker.pkg.dev/your-project-id/your-repo-name/your-image-name:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy your-service-name \
          --image us-central1-docker.pkg.dev/your-project-id/your-repo-name/your-image-name:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
