name: Test Docker Push

on:
  push:
    branches:
      - master

jobs:
  test-docker-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Authenticate Docker using JSON key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcloud-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      


    - name: Build the Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app .

    - name: Push the Docker image
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app
