name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Authenticate Docker with Access Token
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev

    - name: Build the Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-fastapi-app \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars ENV=production,FB_ACCESS_TOKEN=${{ secrets.FB_ACCESS_TOKEN }},FB_CLIENT_ID=${{ secrets.FB_CLIENT_ID }},FB_CLIENT_SECRET=${{ secrets.FB_CLIENT_SECRET }}
