name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build the Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-fastapi-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars ENV=production,FB_ACCESS_TOKEN=${{ secrets.FB_ACCESS_TOKEN }},FB_CLIENT_ID=${{ secrets.FB_CLIENT_ID }},FB_CLIENT_SECRET=${{ secrets.FB_CLIENT_SECRET }}
