name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # Despliega cada vez que se haga push a la rama master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Debug GCP_SA_KEY
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | tr -d '\n' | jq .
      
      
    - name: Authenticate Docker manually
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev


    - name: Build the Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/spygram/spygram-repo/my-fastapi-app .
    
    - name: Push Docker image
      run: |    
        docker push us-central1-docker.pkg.dev/spygram/spygram-repo/my-fastapi-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-fastapi-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated


