name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # Despliega cada vez que se haga push a la rama master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Decode and authenticate Docker manually
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/gcp_key.json
        cat /tmp/gcp_key.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
      
    - name: Set the active account
      run: |
        gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
        gcloud config set account "$(gcloud auth list --filter=status:ACTIVE --format='value(account)')"
      
    - name: Build the Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app .
    
    - name: Push Docker image
      run: |    
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-fastapi-app \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spygram-repo/my-fastapi-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars ENV=production,FB_ACCESS_TOKEN=${{ secrets.FB_ACCESS_TOKEN }},FB_CLIENT_ID=${{ secrets.FB_CLIENT_ID }},FB_CLIENT_SECRET=${{ secrets.FB_CLIENT_SECRET }},SECRET_KEY=${{secrets.SECRET_KEY}}


